### ISSUE TITLE
Point Provider at EU datacenter

### ISSUE THREAD

**Issue by TheMacStack** [dome9/terraform-provider-dome9#101]
We are running a trial of CloudGuard and have our trial account hosted in the checkpoint Europe Datacenter

We are a big Terraform shop so being able to manage CloudGuard/Dome9 via the Terraform provider is a bit of a sales point for us but it seems there is no way to point the provider at the EU DC API?

```
dome9_user.bob: Creating...
Error: FAILED: GET, https://api.dome9.com/v2/user, 401, 401 Invalid username or password, 
  on users.tf line 1, in resource "dome9_user" "bob":
   1: resource "dome9_user" "bob" {
```   

Its possible I am missing something but have triple checked the credentials and actually faced a similar issues with the Dome9 Kubernetes integration where I had to update the deployment to look for the EU api.

**Comment by mzack1985** [comment]
same issue i neet the api.eu1.dome9.com

**Comment by justinhold** [comment]
It doesnt appear to be documented , but the base_url config setting is working for me  
`base_url = "https://api.eu1.dome9.com/v2/"`

**Comment by chkp-dolevh** [comment]
# base_url is an optional field, default value = "https://api.dome9.com/v2/" which route to US region.
provider "dome9" {
  dome9_access_id     = "KEY"
  dome9_secret_key    = "SECRET"
  base_url			  = "URL"
}
