### ISSUE TITLE
AWS GovCloud enrollment

### ISSUE THREAD

**Issue by mlosapio** [dome9/terraform-provider-dome9#102]
Looking through the code, you specifically call out that the role-based access is the only supported method. 

https://github.com/dome9/terraform-provider-dome9/blob/master/dome9/resource_dome9_cloudaccount_aws.go#L76

Also that the iam_user and API key are deprecated
https://github.com/dome9/terraform-provider-dome9/blob/master/dome9/resource_dome9_cloudaccount_aws.go#L71
https://github.com/dome9/terraform-provider-dome9/blob/master/dome9/resource_dome9_cloudaccount_aws.go#L61

I'm happy to chase down the actual parameters that would be needed to make a govcloud account work and make an update to the docs however I don't want to waste the effort if you're going to be rolling out role-based access for govcloud.

**Comment by mlosapio** [comment]
https://github.com/dome9/terraform-provider-dome9/pull/103

**Comment by itzikYeret** [comment]
Hi @mlosapio support have been added. Thanks
