### ISSUE TITLE
Update documentation: "rules" is mandatoy in "dome9_ruleset" 

### ISSUE THREAD

**Issue by javierjeronimo** [dome9/terraform-provider-dome9#106]
Context:
* Terraform 0.15.2
* dome9 provider 1.21.1 (latest)

Creation of a new ruleset fails:
```bash
│ Error: FAILED: POST, https://api.dome9.com/v2/CompliancePolicy, 400, 400 Bad Request, Value cannot be null.
│ Parameter name: source
│ 
│   with module.***.dome9_ruleset.ruleset,
│   on modules/***/main.tf line 3, in resource "dome9_ruleset" "ruleset":
│    3: resource "dome9_ruleset" "ruleset" {
```

Which is weird because in the API documentation there is no such `CompliancePolicy` resource, and `dome9_ruleset` doesn't have `source` attribute.

**Comment by javierjeronimo** [comment]
Ok, this was an error in our implementation. The point is that `rules` block inside `dome9_ruleset` is mandatory, meaning that if you create an *empty* `dome9_ruleset` the apply action will fail with that non-meaningful error.

Documentation in https://registry.terraform.io/providers/dome9/dome9/latest/docs/resources/ruleset should point that `rules` is mandatory and must exist at least one on each `dome9_ruleset`.

**Comment by chkp-dolevh** [comment]
> Ok, this was an error in our implementation. The point is that `rules` block inside `dome9_ruleset` is mandatory, meaning that if you create an _empty_ `dome9_ruleset` the apply action will fail with that non-meaningful error.
> 
> Documentation in https://registry.terraform.io/providers/dome9/dome9/latest/docs/resources/ruleset should point that `rules` is mandatory and must exist at least one on each `dome9_ruleset`.

Will be updated in the next release.
Thanks!

**Comment by chkp-dolevh** [comment]
See v1.24.3
