### ISSUE TITLE
dome9_ruleset - Improvement

### ISSUE THREAD

**Issue by rubenOSX1999** [dome9/terraform-provider-dome9#108]
Good morning!

We are using dome9 terraform provider to promote new rulesets to the tool, but "remediation" property in dome9_ruleset is not available. Could you add please these are the only ones available.

![image](https://user-images.githubusercontent.com/81872069/119106620-d0374380-ba1e-11eb-9348-117259d0a8e2.png)

In fact ruleId and category are also available in the json definition of rules in dome9 and not available in the provider.

Thanks a lot.

**Comment by chkp-dolevh** [comment]
> Good morning!
> 
> We are using dome9 terraform provider to promote new rulesets to the tool, but "remediation" property in dome9_ruleset is not available. Could you add please these are the only ones available.
> 
> ![image](https://user-images.githubusercontent.com/81872069/119106620-d0374380-ba1e-11eb-9348-117259d0a8e2.png)
> 
> In fact ruleId and category are also available in the json definition of rules in dome9 and not available in the provider.
> 
> Thanks a lot.

"remediation" is included at release 1.24 (the provider does not explicitly support it)
The provider explanation that includes "remediation" and many more things will be updated in the next release.

**Comment by chkp-dolevh** [comment]
dome9_ruleset has been updated: v1.24.3
