### ISSUE TITLE
error/mismatch in Azure dome9_cloudaccount_azure documentation  & implmentation

### ISSUE THREAD

**Issue by samqi** [dome9/terraform-provider-dome9#110]
In the Terraform provider [section for dome9_cloudaccount_azure - Argument reference](https://registry.terraform.io/providers/dome9/dome9/latest/docs/resources/cloudaccount_azure#argument-reference),  there is required parameter for **operation_mode**. Documentation shows parameter as "Read-Only" or "Managed" but when applied, I encounter this error message:

`│ Error: expected operation_mode to be one of [Read Manage], got Managed`

The correct parameters are **Read** or **Manage** which works.

Ie: 
`operation_mode         = "Manage"`

**Comment by chkp-dolevh** [comment]
Thanks, fixed
