### ISSUE TITLE
Feature request - Assign account to organization unit during creation

### ISSUE THREAD

**Issue by oryanpeer** [dome9/terraform-provider-dome9#24]
Please allow to assign account to OU during creation and not just on update.
Since terraform is iac it's not make any sense to run the code twice to get the desired request.
If looking on the documentation, we can see that OU is applied only on update state. 

> organizational_unit_id - (Optional) Organizational unit id, Will apply on update state

on the code, we can see it's applied only on the update action - resource_dome9_cloudaccount_gcp.go,  func resourceCloudAccountGCPUpdate:
`	if d.HasChange("organizational_unit_id") {
		log.Println("The organizational unit id has been changed")

		if resp, _, err := d9Client.cloudaccountGCP.UpdateOrganizationalID(d.Id(), gcp.CloudAccountUpdateOrganizationalIDRequest{
			OrganizationalUnitID: d.Get("organizational_unit_id").(string),
		}); err != nil {
			return err
		} else {
			log.Printf("resourceCloudAccountGCPUpdate response is: %+v\n", resp)
		}
	}`

This part does not exists when creating account (func resourceCloudAccountGCPCreate) .
It would be great either you'll split it into 2 different resource so i can do dependencies, or just do the assignment during the account creation.

thanks

**Comment by erezweinstein5-zz** [comment]
Thanks @oryanfarjon for helping us to improve our provider. The issue is known and we are currently working on the solution.

**Comment by erezweinstein5-zz** [comment]
This issue resolved in #29 and it will be released in the next version release
