### ISSUE TITLE
Client_password value showing in TF plan

### ISSUE THREAD

**Issue by nataliapiasek** [dome9/terraform-provider-dome9#45]
It looks like #40 didn't fix the issue with client_password value showing in terraform plan.

**Comment by erezweinstein5-zz** [comment]
Resolved in #47

**Comment by nataliapiasek** [comment]
Thanks so much @erez-dome9, really appreciate this.
When can we expect a new release?

**Comment by erezweinstein5-zz** [comment]
We will try by the end of this week @nataliapiasek
