### ISSUE TITLE
side-bar link mislabeled

### ISSUE THREAD

**Issue by scarbeau** [dome9/terraform-provider-dome9#55]
https://github.com/terraform-providers/terraform-provider-dome9/blob/f456cb8d7874adc7be3a69c51e9d96e6eb5f6653/website/dome9.erb#L44

https://github.com/terraform-providers/terraform-provider-dome9/blob/f456cb8d7874adc7be3a69c51e9d96e6eb5f6653/website/dome9.erb#L84

## L44 Current
```html
<a href="/docs/providers/dome9/d/aws_security_group.html">dome9_ruleset</a>
```

## L44 Revision
```html
<a href="/docs/providers/dome9/d/aws_security_group.html">dome9_aws_security_group</a>
```

Same for L84 Resource link.

**Comment by ayalganem** [comment]
Thanks @scarbeau for helping us to improve our provider. This issue is fixed and changes will take affect in the upcoming release.
