### ISSUE TITLE
dome9_aws_security_group does not return the AWS security group ID

### ISSUE THREAD

**Issue by DanielRis** [dome9/terraform-provider-dome9#75]
The dome9_aws_security_group.external_id property does not return the AWS security group ID, it does return the VPC ID instead.

https://github.com/terraform-providers/terraform-provider-dome9/blob/ebe5681e865777a92623475c4800f8b8e8907c71/dome9/resource_dome9_cloud_security_group_aws.go#L229

should be

`_ = d.Set("external_id", resp.ExternalID)`

I created a PR to fix this #74

**Comment by DanielRis** [comment]
@ayalganem could you please have a look? This bug makes the provider unusable.

**Comment by erezweinstein5-zz** [comment]
@DanielRis thank you for contribution.
We will run our tests against your fix and handle the issue asap.

**Comment by ayalganem** [comment]
Thanks @DanielRis  for helping us to improve our provider, the fix is merged
