### ISSUE TITLE
Feature Request - Add kubernetes_cloud_accounts_count to the cloud account types

### ISSUE THREAD

**Issue by chkp-yonatanph** [dome9/terraform-provider-dome9#87]
There is currently support for aws_cloud_accounts_count , azure_cloud_accounts_count , and gcp_cloud_accounts_count.
Since Kubernetes was added as another type of cloud account, this should be added to the account types as well.

Needs to be added as a Data Source, a Resource, and in the OU commands

**Comment by erezweinstein5-zz** [comment]
Resolved in #88
