### ISSUE TITLE
1.20.1 broke backwards compatibility with 1.20.0

### ISSUE THREAD

**Issue by DanielRis** [dome9/terraform-provider-dome9#92]
Good morning,

could you please be so kind, when you release breaking changes to the provider without releasing a new major version, to ensure backwards compatibility?

It would be great if you could follow this guide https://www.terraform.io/docs/extend/best-practices/deprecations.html to avoid breaking customer code. We pinned our provider to "~> 1.20.0" to include minor bug-fixes but avoid breaking changes.

Thank you very much.

Kind Regards
Daniel

**Comment by erezweinstein5-zz** [comment]
@DanielRis thanks for your feedback again. We will release a new version with backward compatibility soon. You will be notified in this topic and unpin you provider version to enjoy future features

**Comment by DanielRis** [comment]
Thank you @EinatGalilee
